### ISSUE TITLE
Code please!

### ISSUE THREAD

**Issue by perspicacitee** [Younger330/SemanticEnergyLoss#1]
Your work is greatly appreciated, please provide the code as soon as you could. 

Thanks!

**Comment by Younger330** [comment]
> Your work is greatly appreciated, please provide the code as soon as you could.
> 
> Thanks!
Hello @perspicacitee:
Thank you very much for your interest in our work! I apologize for the inconvenience, but I am currently preparing a paper and have not been able to organize and release the code promptly. I will publish our code as soon as possible after completing my paper. Thank you for your understanding and patience!

**Comment by Younger330** [comment]
> Your work is greatly appreciated, please provide the code as soon as you could.
> 
> Thanks!

Hello @perspicacitee 

Thank you very much for your interest in our work! I apologize for the inconvenience, but I am currently preparing a paper and have not been able to organize and release the code promptly. I will publish our code as soon as possible after completing my paper. Thank you for your understanding and patience!

**Comment by Younger330** [comment]
> Your work is greatly appreciated, please provide the code as soon as you could.
> 
> Thanks!


Besides, if it would be helpful, I will upload the code for our loss function in the next few days.

**Comment by Younger330** [comment]
Hello, we have already released our code, so I close this issue. If you have any question, feel free to ask me.
